[package]
name = "btcrs"
version = "0.0.1"
edition = "2021"

[lib]
name = "btcrs"
crate-type = ["cdylib"]

[dependencies]
bitcoin = { version = "0.29.2", features = ["rand"] }
pyo3 = { version = "0.18.0", features = ["extension-module"] }
